# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calib_sample_items.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='calib_sample_items.proto',
  package='car.proto',
  syntax='proto2',
  serialized_pb=_b('\n\x18\x63\x61lib_sample_items.proto\x12\tcar.proto\"=\n\x10\x43\x61libSampleItems\x12)\n\x05items\x18\x01 \x03(\x0b\x32\x1a.car.proto.CalibSampleItem\"\xa7\x01\n\x0f\x43\x61libSampleItem\x12\x14\n\x0clongitudinal\x18\x01 \x02(\x02\x12\x11\n\tspeed_max\x18\x02 \x02(\x02\x12\x11\n\tspeed_min\x18\x03 \x02(\x02\x12+\n\x0b\x61\x63\x63_samples\x18\x04 \x03(\x0b\x32\x16.car.proto.CalibSample\x12+\n\x0b\x64\x65\x63_samples\x18\x05 \x03(\x0b\x32\x16.car.proto.CalibSample\"Q\n\x0b\x43\x61libSample\x12\x0c\n\x04time\x18\x01 \x02(\x03\x12\r\n\x05speed\x18\x02 \x02(\x02\x12\x16\n\x0espeed_filtered\x18\x03 \x02(\x02\x12\r\n\x05\x61\x63\x63\x65l\x18\x04 \x02(\x02')
)




_CALIBSAMPLEITEMS = _descriptor.Descriptor(
  name='CalibSampleItems',
  full_name='car.proto.CalibSampleItems',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='items', full_name='car.proto.CalibSampleItems.items', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=100,
)


_CALIBSAMPLEITEM = _descriptor.Descriptor(
  name='CalibSampleItem',
  full_name='car.proto.CalibSampleItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='longitudinal', full_name='car.proto.CalibSampleItem.longitudinal', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='speed_max', full_name='car.proto.CalibSampleItem.speed_max', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='speed_min', full_name='car.proto.CalibSampleItem.speed_min', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='acc_samples', full_name='car.proto.CalibSampleItem.acc_samples', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dec_samples', full_name='car.proto.CalibSampleItem.dec_samples', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=103,
  serialized_end=270,
)


_CALIBSAMPLE = _descriptor.Descriptor(
  name='CalibSample',
  full_name='car.proto.CalibSample',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='time', full_name='car.proto.CalibSample.time', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='speed', full_name='car.proto.CalibSample.speed', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='speed_filtered', full_name='car.proto.CalibSample.speed_filtered', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='accel', full_name='car.proto.CalibSample.accel', index=3,
      number=4, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=272,
  serialized_end=353,
)

_CALIBSAMPLEITEMS.fields_by_name['items'].message_type = _CALIBSAMPLEITEM
_CALIBSAMPLEITEM.fields_by_name['acc_samples'].message_type = _CALIBSAMPLE
_CALIBSAMPLEITEM.fields_by_name['dec_samples'].message_type = _CALIBSAMPLE
DESCRIPTOR.message_types_by_name['CalibSampleItems'] = _CALIBSAMPLEITEMS
DESCRIPTOR.message_types_by_name['CalibSampleItem'] = _CALIBSAMPLEITEM
DESCRIPTOR.message_types_by_name['CalibSample'] = _CALIBSAMPLE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CalibSampleItems = _reflection.GeneratedProtocolMessageType('CalibSampleItems', (_message.Message,), dict(
  DESCRIPTOR = _CALIBSAMPLEITEMS,
  __module__ = 'calib_sample_items_pb2'
  # @@protoc_insertion_point(class_scope:car.proto.CalibSampleItems)
  ))
_sym_db.RegisterMessage(CalibSampleItems)

CalibSampleItem = _reflection.GeneratedProtocolMessageType('CalibSampleItem', (_message.Message,), dict(
  DESCRIPTOR = _CALIBSAMPLEITEM,
  __module__ = 'calib_sample_items_pb2'
  # @@protoc_insertion_point(class_scope:car.proto.CalibSampleItem)
  ))
_sym_db.RegisterMessage(CalibSampleItem)

CalibSample = _reflection.GeneratedProtocolMessageType('CalibSample', (_message.Message,), dict(
  DESCRIPTOR = _CALIBSAMPLE,
  __module__ = 'calib_sample_items_pb2'
  # @@protoc_insertion_point(class_scope:car.proto.CalibSample)
  ))
_sym_db.RegisterMessage(CalibSample)


# @@protoc_insertion_point(module_scope)
