# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: config_canbus.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='config_canbus.proto',
  package='car.proto',
  syntax='proto2',
  serialized_pb=_b('\n\x13\x63onfig_canbus.proto\x12\tcar.proto\"\xe1\x01\n\nCanChannel\x12\x0f\n\x07\x63hannel\x18\x01 \x01(\x05\x12\x17\n\nbit_rate_k\x18\x02 \x01(\x05:\x03\x35\x30\x30\x12\x1d\n\x0fread_timeout_us\x18\x03 \x01(\x05:\x04\x31\x30\x30\x30\x12\x1e\n\x10write_timeout_us\x18\x04 \x01(\x05:\x04\x31\x30\x30\x30\x12\x16\n\x0b\x61\x63\x63\x65pt_code\x18\x05 \x01(\r:\x01\x30\x12\x16\n\x0b\x61\x63\x63\x65pt_mask\x18\x06 \x01(\r:\x01\x30\x12\x11\n\tremote_ip\x18\x07 \x01(\t\x12\x13\n\x0bremote_port\x18\x08 \x01(\x05\x12\x12\n\nlocal_port\x18\t \x01(\x05\"\xae\x01\n\x0c\x43\x61nInterface\x12\x36\n\x04type\x18\x01 \x01(\x0e\x32(.car.proto.CanInterface.CanInterfaceType\x12\'\n\x08\x63hannels\x18\x02 \x03(\x0b\x32\x15.car.proto.CanChannel\"=\n\x10\x43\x61nInterfaceType\x12\x0b\n\x07INVALID\x10\x00\x12\x0b\n\x07VIRTUAL\x10\x01\x12\x0f\n\x0bKVASER_PCIE\x10\x02\"\xa3\x01\n\x0c\x43onfigCanbus\x12*\n\tinterface\x18\x01 \x01(\x0b\x32\x17.car.proto.CanInterface\x12\x33\n\tcar_model\x18\x02 \x01(\x0e\x32 .car.proto.ConfigCanbus.CarModel\"2\n\x08\x43\x61rModel\x12\x0b\n\x07INVALID\x10\x00\x12\x07\n\x03MKZ\x10\x01\x12\x07\n\x03\x45\x37\x30\x10\x02\x12\x07\n\x03\x46MS\x10\x03')
)



_CANINTERFACE_CANINTERFACETYPE = _descriptor.EnumDescriptor(
  name='CanInterfaceType',
  full_name='car.proto.CanInterface.CanInterfaceType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='INVALID', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VIRTUAL', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='KVASER_PCIE', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=376,
  serialized_end=437,
)
_sym_db.RegisterEnumDescriptor(_CANINTERFACE_CANINTERFACETYPE)

_CONFIGCANBUS_CARMODEL = _descriptor.EnumDescriptor(
  name='CarModel',
  full_name='car.proto.ConfigCanbus.CarModel',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='INVALID', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MKZ', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='E70', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FMS', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=553,
  serialized_end=603,
)
_sym_db.RegisterEnumDescriptor(_CONFIGCANBUS_CARMODEL)


_CANCHANNEL = _descriptor.Descriptor(
  name='CanChannel',
  full_name='car.proto.CanChannel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='channel', full_name='car.proto.CanChannel.channel', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bit_rate_k', full_name='car.proto.CanChannel.bit_rate_k', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=500,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='read_timeout_us', full_name='car.proto.CanChannel.read_timeout_us', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=1000,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='write_timeout_us', full_name='car.proto.CanChannel.write_timeout_us', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=1000,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='accept_code', full_name='car.proto.CanChannel.accept_code', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='accept_mask', full_name='car.proto.CanChannel.accept_mask', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='remote_ip', full_name='car.proto.CanChannel.remote_ip', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='remote_port', full_name='car.proto.CanChannel.remote_port', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='local_port', full_name='car.proto.CanChannel.local_port', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=260,
)


_CANINTERFACE = _descriptor.Descriptor(
  name='CanInterface',
  full_name='car.proto.CanInterface',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='car.proto.CanInterface.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='channels', full_name='car.proto.CanInterface.channels', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _CANINTERFACE_CANINTERFACETYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=263,
  serialized_end=437,
)


_CONFIGCANBUS = _descriptor.Descriptor(
  name='ConfigCanbus',
  full_name='car.proto.ConfigCanbus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='interface', full_name='car.proto.ConfigCanbus.interface', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='car_model', full_name='car.proto.ConfigCanbus.car_model', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _CONFIGCANBUS_CARMODEL,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=440,
  serialized_end=603,
)

_CANINTERFACE.fields_by_name['type'].enum_type = _CANINTERFACE_CANINTERFACETYPE
_CANINTERFACE.fields_by_name['channels'].message_type = _CANCHANNEL
_CANINTERFACE_CANINTERFACETYPE.containing_type = _CANINTERFACE
_CONFIGCANBUS.fields_by_name['interface'].message_type = _CANINTERFACE
_CONFIGCANBUS.fields_by_name['car_model'].enum_type = _CONFIGCANBUS_CARMODEL
_CONFIGCANBUS_CARMODEL.containing_type = _CONFIGCANBUS
DESCRIPTOR.message_types_by_name['CanChannel'] = _CANCHANNEL
DESCRIPTOR.message_types_by_name['CanInterface'] = _CANINTERFACE
DESCRIPTOR.message_types_by_name['ConfigCanbus'] = _CONFIGCANBUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CanChannel = _reflection.GeneratedProtocolMessageType('CanChannel', (_message.Message,), dict(
  DESCRIPTOR = _CANCHANNEL,
  __module__ = 'config_canbus_pb2'
  # @@protoc_insertion_point(class_scope:car.proto.CanChannel)
  ))
_sym_db.RegisterMessage(CanChannel)

CanInterface = _reflection.GeneratedProtocolMessageType('CanInterface', (_message.Message,), dict(
  DESCRIPTOR = _CANINTERFACE,
  __module__ = 'config_canbus_pb2'
  # @@protoc_insertion_point(class_scope:car.proto.CanInterface)
  ))
_sym_db.RegisterMessage(CanInterface)

ConfigCanbus = _reflection.GeneratedProtocolMessageType('ConfigCanbus', (_message.Message,), dict(
  DESCRIPTOR = _CONFIGCANBUS,
  __module__ = 'config_canbus_pb2'
  # @@protoc_insertion_point(class_scope:car.proto.ConfigCanbus)
  ))
_sym_db.RegisterMessage(ConfigCanbus)


# @@protoc_insertion_point(module_scope)
