# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: config_camera.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import geometry_pb2 as geometry__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='config_camera.proto',
  package='car.proto',
  syntax='proto2',
  serialized_pb=_b('\n\x13\x63onfig_camera.proto\x12\tcar.proto\x1a\x0egeometry.proto\"\xbb\x03\n\x0c\x43onfigCamera\x12\x0c\n\x04name\x18\x01 \x01(\x0c\x12\x15\n\rserial_number\x18\x02 \x01(\x0c\x12\x19\n\x0bimage_width\x18\x03 \x01(\x05:\x04\x31\x39\x32\x30\x12\x1a\n\x0cimage_height\x18\x04 \x01(\x05:\x04\x31\x32\x30\x30\x12\x12\n\nframe_rate\x18\x05 \x01(\x02\x12\x36\n\x11sensing_to_camera\x18\x06 \x01(\x0b\x32\x1b.car.proto.Transformation3f\x12\n\n\x02\x66x\x18\x07 \x01(\x02\x12\n\n\x02\x66y\x18\x08 \x01(\x02\x12\n\n\x02ox\x18\t \x01(\x02\x12\n\n\x02oy\x18\n \x01(\x02\x12\x19\n\x11radial_distortion\x18\x0b \x03(\x02\x12\x1d\n\x11\x65xposure_time_min\x18\x0c \x01(\x05:\x02\x35\x30\x12 \n\x11\x65xposure_time_max\x18\r \x01(\x05:\x05\x32\x30\x30\x30\x30\x12\x18\n\treverse_x\x18\x0e \x01(\x08:\x05\x66\x61lse\x12\x18\n\treverse_y\x18\x0f \x01(\x08:\x05\x66\x61lse\x12\x1e\n\x13image_height_offset\x18\x10 \x01(\x05:\x01\x30\x12#\n\x0eimage_encoding\x18\x11 \x01(\x0c:\x0b\x62\x61yer_rggb8\"\x8b\x01\n\rConfigCameras\x12(\n\x07\x63\x61meras\x18\x01 \x03(\x0b\x32\x17.car.proto.ConfigCamera\x12\x37\n\x12vehicle_to_sensing\x18\x02 \x01(\x0b\x32\x1b.car.proto.Transformation3f\x12\x17\n\x0fimage_directory\x18\x03 \x01(\x0c')
  ,
  dependencies=[geometry__pb2.DESCRIPTOR,])




_CONFIGCAMERA = _descriptor.Descriptor(
  name='ConfigCamera',
  full_name='car.proto.ConfigCamera',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='car.proto.ConfigCamera.name', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='serial_number', full_name='car.proto.ConfigCamera.serial_number', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='image_width', full_name='car.proto.ConfigCamera.image_width', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=1920,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='image_height', full_name='car.proto.ConfigCamera.image_height', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=1200,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='frame_rate', full_name='car.proto.ConfigCamera.frame_rate', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sensing_to_camera', full_name='car.proto.ConfigCamera.sensing_to_camera', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fx', full_name='car.proto.ConfigCamera.fx', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fy', full_name='car.proto.ConfigCamera.fy', index=7,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ox', full_name='car.proto.ConfigCamera.ox', index=8,
      number=9, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='oy', full_name='car.proto.ConfigCamera.oy', index=9,
      number=10, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='radial_distortion', full_name='car.proto.ConfigCamera.radial_distortion', index=10,
      number=11, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='exposure_time_min', full_name='car.proto.ConfigCamera.exposure_time_min', index=11,
      number=12, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=50,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='exposure_time_max', full_name='car.proto.ConfigCamera.exposure_time_max', index=12,
      number=13, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=20000,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='reverse_x', full_name='car.proto.ConfigCamera.reverse_x', index=13,
      number=14, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='reverse_y', full_name='car.proto.ConfigCamera.reverse_y', index=14,
      number=15, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='image_height_offset', full_name='car.proto.ConfigCamera.image_height_offset', index=15,
      number=16, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='image_encoding', full_name='car.proto.ConfigCamera.image_encoding', index=16,
      number=17, type=12, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("bayer_rggb8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=494,
)


_CONFIGCAMERAS = _descriptor.Descriptor(
  name='ConfigCameras',
  full_name='car.proto.ConfigCameras',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cameras', full_name='car.proto.ConfigCameras.cameras', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='vehicle_to_sensing', full_name='car.proto.ConfigCameras.vehicle_to_sensing', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='image_directory', full_name='car.proto.ConfigCameras.image_directory', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=497,
  serialized_end=636,
)

_CONFIGCAMERA.fields_by_name['sensing_to_camera'].message_type = geometry__pb2._TRANSFORMATION3F
_CONFIGCAMERAS.fields_by_name['cameras'].message_type = _CONFIGCAMERA
_CONFIGCAMERAS.fields_by_name['vehicle_to_sensing'].message_type = geometry__pb2._TRANSFORMATION3F
DESCRIPTOR.message_types_by_name['ConfigCamera'] = _CONFIGCAMERA
DESCRIPTOR.message_types_by_name['ConfigCameras'] = _CONFIGCAMERAS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ConfigCamera = _reflection.GeneratedProtocolMessageType('ConfigCamera', (_message.Message,), dict(
  DESCRIPTOR = _CONFIGCAMERA,
  __module__ = 'config_camera_pb2'
  # @@protoc_insertion_point(class_scope:car.proto.ConfigCamera)
  ))
_sym_db.RegisterMessage(ConfigCamera)

ConfigCameras = _reflection.GeneratedProtocolMessageType('ConfigCameras', (_message.Message,), dict(
  DESCRIPTOR = _CONFIGCAMERAS,
  __module__ = 'config_camera_pb2'
  # @@protoc_insertion_point(class_scope:car.proto.ConfigCameras)
  ))
_sym_db.RegisterMessage(ConfigCameras)


# @@protoc_insertion_point(module_scope)
