# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: config_calib.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='config_calib.proto',
  package='car.proto',
  syntax='proto2',
  serialized_pb=_b('\n\x12\x63onfig_calib.proto\x12\tcar.proto\"I\n\x0b\x43onfigCalib\x12\x11\n\tspeed_max\x18\x01 \x02(\x02\x12\x11\n\tspeed_min\x18\x02 \x02(\x02\x12\x14\n\x0clongitudinal\x18\x03 \x03(\x02')
)




_CONFIGCALIB = _descriptor.Descriptor(
  name='ConfigCalib',
  full_name='car.proto.ConfigCalib',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='speed_max', full_name='car.proto.ConfigCalib.speed_max', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='speed_min', full_name='car.proto.ConfigCalib.speed_min', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='longitudinal', full_name='car.proto.ConfigCalib.longitudinal', index=2,
      number=3, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=106,
)

DESCRIPTOR.message_types_by_name['ConfigCalib'] = _CONFIGCALIB
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ConfigCalib = _reflection.GeneratedProtocolMessageType('ConfigCalib', (_message.Message,), dict(
  DESCRIPTOR = _CONFIGCALIB,
  __module__ = 'config_calib_pb2'
  # @@protoc_insertion_point(class_scope:car.proto.ConfigCalib)
  ))
_sym_db.RegisterMessage(ConfigCalib)


# @@protoc_insertion_point(module_scope)
