# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: config_car.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import geometry_pb2 as geometry__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='config_car.proto',
  package='car.proto',
  syntax='proto2',
  serialized_pb=_b('\n\x10\x63onfig_car.proto\x12\tcar.proto\x1a\x0egeometry.proto\"\xc2\x07\n\tConfigCar\x12\x19\n\x11\x66ront_edge_to_vrp\x18\x01 \x01(\x02\x12\x18\n\x10rear_edge_to_vrp\x18\x02 \x01(\x02\x12\x18\n\x10left_edge_to_vrp\x18\x03 \x01(\x02\x12\x19\n\x11right_edge_to_vrp\x18\x04 \x01(\x02\x12\x0e\n\x06height\x18\x05 \x01(\x02\x12.\n\x11\x63\x65nter_of_gravity\x18\x06 \x01(\x0b\x32\x13.car.proto.Vector3f\x12\x12\n\nwheel_base\x18\x07 \x01(\x02\x12\x0c\n\x04mass\x18\x08 \x01(\x02\x12\x0f\n\x07inertia\x18\t \x01(\x02\x12\x1c\n\x14wheel_rolling_radius\x18\n \x01(\x02\x12\x15\n\rc_alpha_front\x18\x0b \x01(\x02\x12\x14\n\x0c\x63_alpha_rear\x18\x0c \x01(\x02\x12\x16\n\x0e\x63_torque_front\x18\r \x01(\x02\x12\x15\n\rc_torque_rear\x18\x0e \x01(\x02\x12\x1d\n\x12\x61\x63\x63\x65leration_limit\x18\x0f \x01(\x02:\x01\x31\x12\x1d\n\x12\x64\x65\x63\x65leration_limit\x18\x10 \x01(\x02:\x01\x33\x12)\n\x1cstop_line_acceleration_limit\x18\x11 \x01(\x02:\x03\x31.5\x12\'\n\x1cstop_line_deceleration_limit\x18\x12 \x01(\x02:\x01\x35\x12$\n\x17\x61\x63\x63\x65leration_jerk_limit\x18\x13 \x01(\x02:\x03\x31.5\x12$\n\x17\x64\x65\x63\x65leration_jerk_limit\x18\x14 \x01(\x02:\x03\x32.5\x12.\n!stop_line_acceleration_jerk_limit\x18\x15 \x01(\x02:\x03\x31.5\x12,\n!stop_line_deceleration_jerk_limit\x18\x16 \x01(\x02:\x01\x34\x12\x17\n\x0fmin_turn_radius\x18\x17 \x01(\x02\x12\x13\n\x0b\x61ngle_limit\x18\x18 \x01(\x02\x12\x17\n\x0f\x61ngle_slew_rate\x18\x19 \x01(\x02\x12\x16\n\x0esteering_ratio\x18\x1a \x01(\x02\x12\x19\n\x11lateral_acc_limit\x18\x1b \x01(\x02\x12\x1d\n\x15throttle_deadzone_low\x18\x1c \x01(\x02\x12\x1c\n\x14throttle_deadzone_up\x18\x1d \x01(\x02\x12\x1a\n\x12\x62rake_deadzone_low\x18\x1e \x01(\x02\x12\x19\n\x11\x62rake_deadzone_up\x18\x1f \x01(\x02\x12\x15\n\npitch_bias\x18  \x01(\x02:\x01\x30\x12\x1d\n\x11\x63ontrol_frequency\x18! \x01(\x02:\x02\x35\x30')
  ,
  dependencies=[geometry__pb2.DESCRIPTOR,])




_CONFIGCAR = _descriptor.Descriptor(
  name='ConfigCar',
  full_name='car.proto.ConfigCar',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='front_edge_to_vrp', full_name='car.proto.ConfigCar.front_edge_to_vrp', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rear_edge_to_vrp', full_name='car.proto.ConfigCar.rear_edge_to_vrp', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='left_edge_to_vrp', full_name='car.proto.ConfigCar.left_edge_to_vrp', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='right_edge_to_vrp', full_name='car.proto.ConfigCar.right_edge_to_vrp', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='height', full_name='car.proto.ConfigCar.height', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='center_of_gravity', full_name='car.proto.ConfigCar.center_of_gravity', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='wheel_base', full_name='car.proto.ConfigCar.wheel_base', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mass', full_name='car.proto.ConfigCar.mass', index=7,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='inertia', full_name='car.proto.ConfigCar.inertia', index=8,
      number=9, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='wheel_rolling_radius', full_name='car.proto.ConfigCar.wheel_rolling_radius', index=9,
      number=10, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='c_alpha_front', full_name='car.proto.ConfigCar.c_alpha_front', index=10,
      number=11, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='c_alpha_rear', full_name='car.proto.ConfigCar.c_alpha_rear', index=11,
      number=12, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='c_torque_front', full_name='car.proto.ConfigCar.c_torque_front', index=12,
      number=13, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='c_torque_rear', full_name='car.proto.ConfigCar.c_torque_rear', index=13,
      number=14, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='acceleration_limit', full_name='car.proto.ConfigCar.acceleration_limit', index=14,
      number=15, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(1),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='deceleration_limit', full_name='car.proto.ConfigCar.deceleration_limit', index=15,
      number=16, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(3),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stop_line_acceleration_limit', full_name='car.proto.ConfigCar.stop_line_acceleration_limit', index=16,
      number=17, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(1.5),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stop_line_deceleration_limit', full_name='car.proto.ConfigCar.stop_line_deceleration_limit', index=17,
      number=18, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(5),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='acceleration_jerk_limit', full_name='car.proto.ConfigCar.acceleration_jerk_limit', index=18,
      number=19, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(1.5),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='deceleration_jerk_limit', full_name='car.proto.ConfigCar.deceleration_jerk_limit', index=19,
      number=20, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(2.5),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stop_line_acceleration_jerk_limit', full_name='car.proto.ConfigCar.stop_line_acceleration_jerk_limit', index=20,
      number=21, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(1.5),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stop_line_deceleration_jerk_limit', full_name='car.proto.ConfigCar.stop_line_deceleration_jerk_limit', index=21,
      number=22, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(4),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='min_turn_radius', full_name='car.proto.ConfigCar.min_turn_radius', index=22,
      number=23, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='angle_limit', full_name='car.proto.ConfigCar.angle_limit', index=23,
      number=24, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='angle_slew_rate', full_name='car.proto.ConfigCar.angle_slew_rate', index=24,
      number=25, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='steering_ratio', full_name='car.proto.ConfigCar.steering_ratio', index=25,
      number=26, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lateral_acc_limit', full_name='car.proto.ConfigCar.lateral_acc_limit', index=26,
      number=27, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='throttle_deadzone_low', full_name='car.proto.ConfigCar.throttle_deadzone_low', index=27,
      number=28, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='throttle_deadzone_up', full_name='car.proto.ConfigCar.throttle_deadzone_up', index=28,
      number=29, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='brake_deadzone_low', full_name='car.proto.ConfigCar.brake_deadzone_low', index=29,
      number=30, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='brake_deadzone_up', full_name='car.proto.ConfigCar.brake_deadzone_up', index=30,
      number=31, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pitch_bias', full_name='car.proto.ConfigCar.pitch_bias', index=31,
      number=32, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='control_frequency', full_name='car.proto.ConfigCar.control_frequency', index=32,
      number=33, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(50),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=1010,
)

_CONFIGCAR.fields_by_name['center_of_gravity'].message_type = geometry__pb2._VECTOR3F
DESCRIPTOR.message_types_by_name['ConfigCar'] = _CONFIGCAR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ConfigCar = _reflection.GeneratedProtocolMessageType('ConfigCar', (_message.Message,), dict(
  DESCRIPTOR = _CONFIGCAR,
  __module__ = 'config_car_pb2'
  # @@protoc_insertion_point(class_scope:car.proto.ConfigCar)
  ))
_sym_db.RegisterMessage(ConfigCar)


# @@protoc_insertion_point(module_scope)
