# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: control_command.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import car_state_pb2 as car__state__pb2
import car_info_pb2 as car__info__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='control_command.proto',
  package='car.proto',
  syntax='proto2',
  serialized_pb=_b('\n\x15\x63ontrol_command.proto\x12\tcar.proto\x1a\x0f\x63\x61r_state.proto\x1a\x0e\x63\x61r_info.proto\"\x83\x05\n\x0e\x43ontrolCommand\x12\x0f\n\x05\x61ngle\x18\x01 \x01(\x02H\x00\x12\x10\n\x06torque\x18\x02 \x01(\x02H\x00\x12\x1e\n\x16\x66ront_wheel_angle_rate\x18\x03 \x01(\x02\x12\x14\n\x0c\x61\x63\x63\x65leration\x18\x04 \x01(\x02\x12\x10\n\x08throttle\x18\x05 \x01(\x02\x12\x33\n\x0bturn_signal\x18\x06 \x01(\x0e\x32\x1e.car.proto.CarState.TurnSignal\x12!\n\x19warning_blinker_signal_on\x18\x07 \x01(\x08\x12,\n\x04gear\x18\x08 \x01(\x0e\x32\x1e.car.proto.CarState.GearStatus\x12\x35\n\x0c\x64riving_mode\x18\t \x01(\x0e\x32\x1f.car.proto.CarState.DrivingMode\x12\r\n\x05speed\x18\n \x01(\x02\x12\x11\n\tauto_mode\x18\x0b \x01(\x08\x12\x13\n\x0bmarker_lamp\x18\x0c \x01(\x08\x12\x13\n\x0b\x62rake_light\x18\r \x01(\x08\x12\x0c\n\x04horn\x18\x0e \x01(\x08\x12\"\n\x04\x62\x65\x61m\x18\x0f \x01(\x0e\x32\x14.car.proto.Misc.Beam\x12\x12\n\nlon_status\x18\x10 \x01(\r\x12\x1e\n\x16\x65go_front_to_lead_rear\x18\x11 \x01(\x02\x12\x14\n\x0clongitudinal\x18\x12 \x01(\x02\x12@\n\x12hazard_ctrl_signal\x18\x13 \x01(\x0e\x32$.car.proto.CarState.HazardCtrlSignal\x12\x1c\n\x14\x41\x45\x42_brake_triggered_\x18\x14 \x01(\x08\x12\x12\n\nAEB_brake_\x18\x15 \x01(\x01\x42\r\n\x0b\x66ront_wheel')
  ,
  dependencies=[car__state__pb2.DESCRIPTOR,car__info__pb2.DESCRIPTOR,])




_CONTROLCOMMAND = _descriptor.Descriptor(
  name='ControlCommand',
  full_name='car.proto.ControlCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='angle', full_name='car.proto.ControlCommand.angle', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='torque', full_name='car.proto.ControlCommand.torque', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='front_wheel_angle_rate', full_name='car.proto.ControlCommand.front_wheel_angle_rate', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='acceleration', full_name='car.proto.ControlCommand.acceleration', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='throttle', full_name='car.proto.ControlCommand.throttle', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='turn_signal', full_name='car.proto.ControlCommand.turn_signal', index=5,
      number=6, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='warning_blinker_signal_on', full_name='car.proto.ControlCommand.warning_blinker_signal_on', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gear', full_name='car.proto.ControlCommand.gear', index=7,
      number=8, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='driving_mode', full_name='car.proto.ControlCommand.driving_mode', index=8,
      number=9, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='speed', full_name='car.proto.ControlCommand.speed', index=9,
      number=10, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='auto_mode', full_name='car.proto.ControlCommand.auto_mode', index=10,
      number=11, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='marker_lamp', full_name='car.proto.ControlCommand.marker_lamp', index=11,
      number=12, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='brake_light', full_name='car.proto.ControlCommand.brake_light', index=12,
      number=13, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='horn', full_name='car.proto.ControlCommand.horn', index=13,
      number=14, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='beam', full_name='car.proto.ControlCommand.beam', index=14,
      number=15, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lon_status', full_name='car.proto.ControlCommand.lon_status', index=15,
      number=16, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ego_front_to_lead_rear', full_name='car.proto.ControlCommand.ego_front_to_lead_rear', index=16,
      number=17, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='longitudinal', full_name='car.proto.ControlCommand.longitudinal', index=17,
      number=18, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hazard_ctrl_signal', full_name='car.proto.ControlCommand.hazard_ctrl_signal', index=18,
      number=19, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='AEB_brake_triggered_', full_name='car.proto.ControlCommand.AEB_brake_triggered_', index=19,
      number=20, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='AEB_brake_', full_name='car.proto.ControlCommand.AEB_brake_', index=20,
      number=21, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='front_wheel', full_name='car.proto.ControlCommand.front_wheel',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=70,
  serialized_end=713,
)

_CONTROLCOMMAND.fields_by_name['turn_signal'].enum_type = car__state__pb2._CARSTATE_TURNSIGNAL
_CONTROLCOMMAND.fields_by_name['gear'].enum_type = car__state__pb2._CARSTATE_GEARSTATUS
_CONTROLCOMMAND.fields_by_name['driving_mode'].enum_type = car__state__pb2._CARSTATE_DRIVINGMODE
_CONTROLCOMMAND.fields_by_name['beam'].enum_type = car__info__pb2._MISC_BEAM
_CONTROLCOMMAND.fields_by_name['hazard_ctrl_signal'].enum_type = car__state__pb2._CARSTATE_HAZARDCTRLSIGNAL
_CONTROLCOMMAND.oneofs_by_name['front_wheel'].fields.append(
  _CONTROLCOMMAND.fields_by_name['angle'])
_CONTROLCOMMAND.fields_by_name['angle'].containing_oneof = _CONTROLCOMMAND.oneofs_by_name['front_wheel']
_CONTROLCOMMAND.oneofs_by_name['front_wheel'].fields.append(
  _CONTROLCOMMAND.fields_by_name['torque'])
_CONTROLCOMMAND.fields_by_name['torque'].containing_oneof = _CONTROLCOMMAND.oneofs_by_name['front_wheel']
DESCRIPTOR.message_types_by_name['ControlCommand'] = _CONTROLCOMMAND
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ControlCommand = _reflection.GeneratedProtocolMessageType('ControlCommand', (_message.Message,), dict(
  DESCRIPTOR = _CONTROLCOMMAND,
  __module__ = 'control_command_pb2'
  # @@protoc_insertion_point(class_scope:car.proto.ControlCommand)
  ))
_sym_db.RegisterMessage(ControlCommand)


# @@protoc_insertion_point(module_scope)
