# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: geometry.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='geometry.proto',
  package='car.proto',
  syntax='proto2',
  serialized_pb=_b('\n\x0egeometry.proto\x12\tcar.proto\"+\n\x08Vector3d\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\"+\n\x08Vector3f\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\"<\n\x0bQuaterniond\x12\x0c\n\x01w\x18\x01 \x01(\x01:\x01\x31\x12\t\n\x01x\x18\x02 \x01(\x01\x12\t\n\x01y\x18\x03 \x01(\x01\x12\t\n\x01z\x18\x04 \x01(\x01\"<\n\x0bQuaternionf\x12\x0c\n\x01w\x18\x01 \x01(\x02:\x01\x31\x12\t\n\x01x\x18\x02 \x01(\x02\x12\t\n\x01y\x18\x03 \x01(\x02\x12\t\n\x01z\x18\x04 \x01(\x02\"f\n\x10Transformation3d\x12%\n\x08position\x18\x01 \x01(\x0b\x32\x13.car.proto.Vector3d\x12+\n\x0borientation\x18\x02 \x01(\x0b\x32\x16.car.proto.Quaterniond\"f\n\x10Transformation3f\x12%\n\x08position\x18\x01 \x01(\x0b\x32\x13.car.proto.Vector3f\x12+\n\x0borientation\x18\x02 \x01(\x0b\x32\x16.car.proto.Quaternionf\".\n\x07Polygon\x12#\n\x06points\x18\x01 \x03(\x0b\x32\x13.car.proto.Vector3f\"/\n\x08Polyline\x12#\n\x06points\x18\x01 \x03(\x0b\x32\x13.car.proto.Vector3f')
)




_VECTOR3D = _descriptor.Descriptor(
  name='Vector3d',
  full_name='car.proto.Vector3d',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='car.proto.Vector3d.x', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='car.proto.Vector3d.y', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z', full_name='car.proto.Vector3d.z', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=72,
)


_VECTOR3F = _descriptor.Descriptor(
  name='Vector3f',
  full_name='car.proto.Vector3f',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='car.proto.Vector3f.x', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='car.proto.Vector3f.y', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z', full_name='car.proto.Vector3f.z', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=117,
)


_QUATERNIOND = _descriptor.Descriptor(
  name='Quaterniond',
  full_name='car.proto.Quaterniond',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='w', full_name='car.proto.Quaterniond.w', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(1),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='x', full_name='car.proto.Quaterniond.x', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='car.proto.Quaterniond.y', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z', full_name='car.proto.Quaterniond.z', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=119,
  serialized_end=179,
)


_QUATERNIONF = _descriptor.Descriptor(
  name='Quaternionf',
  full_name='car.proto.Quaternionf',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='w', full_name='car.proto.Quaternionf.w', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(1),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='x', full_name='car.proto.Quaternionf.x', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='car.proto.Quaternionf.y', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z', full_name='car.proto.Quaternionf.z', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=181,
  serialized_end=241,
)


_TRANSFORMATION3D = _descriptor.Descriptor(
  name='Transformation3d',
  full_name='car.proto.Transformation3d',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='position', full_name='car.proto.Transformation3d.position', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='orientation', full_name='car.proto.Transformation3d.orientation', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=243,
  serialized_end=345,
)


_TRANSFORMATION3F = _descriptor.Descriptor(
  name='Transformation3f',
  full_name='car.proto.Transformation3f',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='position', full_name='car.proto.Transformation3f.position', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='orientation', full_name='car.proto.Transformation3f.orientation', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=347,
  serialized_end=449,
)


_POLYGON = _descriptor.Descriptor(
  name='Polygon',
  full_name='car.proto.Polygon',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='points', full_name='car.proto.Polygon.points', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=451,
  serialized_end=497,
)


_POLYLINE = _descriptor.Descriptor(
  name='Polyline',
  full_name='car.proto.Polyline',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='points', full_name='car.proto.Polyline.points', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=499,
  serialized_end=546,
)

_TRANSFORMATION3D.fields_by_name['position'].message_type = _VECTOR3D
_TRANSFORMATION3D.fields_by_name['orientation'].message_type = _QUATERNIOND
_TRANSFORMATION3F.fields_by_name['position'].message_type = _VECTOR3F
_TRANSFORMATION3F.fields_by_name['orientation'].message_type = _QUATERNIONF
_POLYGON.fields_by_name['points'].message_type = _VECTOR3F
_POLYLINE.fields_by_name['points'].message_type = _VECTOR3F
DESCRIPTOR.message_types_by_name['Vector3d'] = _VECTOR3D
DESCRIPTOR.message_types_by_name['Vector3f'] = _VECTOR3F
DESCRIPTOR.message_types_by_name['Quaterniond'] = _QUATERNIOND
DESCRIPTOR.message_types_by_name['Quaternionf'] = _QUATERNIONF
DESCRIPTOR.message_types_by_name['Transformation3d'] = _TRANSFORMATION3D
DESCRIPTOR.message_types_by_name['Transformation3f'] = _TRANSFORMATION3F
DESCRIPTOR.message_types_by_name['Polygon'] = _POLYGON
DESCRIPTOR.message_types_by_name['Polyline'] = _POLYLINE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Vector3d = _reflection.GeneratedProtocolMessageType('Vector3d', (_message.Message,), dict(
  DESCRIPTOR = _VECTOR3D,
  __module__ = 'geometry_pb2'
  # @@protoc_insertion_point(class_scope:car.proto.Vector3d)
  ))
_sym_db.RegisterMessage(Vector3d)

Vector3f = _reflection.GeneratedProtocolMessageType('Vector3f', (_message.Message,), dict(
  DESCRIPTOR = _VECTOR3F,
  __module__ = 'geometry_pb2'
  # @@protoc_insertion_point(class_scope:car.proto.Vector3f)
  ))
_sym_db.RegisterMessage(Vector3f)

Quaterniond = _reflection.GeneratedProtocolMessageType('Quaterniond', (_message.Message,), dict(
  DESCRIPTOR = _QUATERNIOND,
  __module__ = 'geometry_pb2'
  # @@protoc_insertion_point(class_scope:car.proto.Quaterniond)
  ))
_sym_db.RegisterMessage(Quaterniond)

Quaternionf = _reflection.GeneratedProtocolMessageType('Quaternionf', (_message.Message,), dict(
  DESCRIPTOR = _QUATERNIONF,
  __module__ = 'geometry_pb2'
  # @@protoc_insertion_point(class_scope:car.proto.Quaternionf)
  ))
_sym_db.RegisterMessage(Quaternionf)

Transformation3d = _reflection.GeneratedProtocolMessageType('Transformation3d', (_message.Message,), dict(
  DESCRIPTOR = _TRANSFORMATION3D,
  __module__ = 'geometry_pb2'
  # @@protoc_insertion_point(class_scope:car.proto.Transformation3d)
  ))
_sym_db.RegisterMessage(Transformation3d)

Transformation3f = _reflection.GeneratedProtocolMessageType('Transformation3f', (_message.Message,), dict(
  DESCRIPTOR = _TRANSFORMATION3F,
  __module__ = 'geometry_pb2'
  # @@protoc_insertion_point(class_scope:car.proto.Transformation3f)
  ))
_sym_db.RegisterMessage(Transformation3f)

Polygon = _reflection.GeneratedProtocolMessageType('Polygon', (_message.Message,), dict(
  DESCRIPTOR = _POLYGON,
  __module__ = 'geometry_pb2'
  # @@protoc_insertion_point(class_scope:car.proto.Polygon)
  ))
_sym_db.RegisterMessage(Polygon)

Polyline = _reflection.GeneratedProtocolMessageType('Polyline', (_message.Message,), dict(
  DESCRIPTOR = _POLYLINE,
  __module__ = 'geometry_pb2'
  # @@protoc_insertion_point(class_scope:car.proto.Polyline)
  ))
_sym_db.RegisterMessage(Polyline)


# @@protoc_insertion_point(module_scope)
