# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: perception_signal.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='perception_signal.proto',
  package='car.proto',
  syntax='proto2',
  serialized_pb=_b('\n\x17perception_signal.proto\x12\tcar.proto\"\xd5\x01\n\x10PerceptionSignal\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x35\n\x06\x63olors\x18\x02 \x03(\x0e\x32!.car.proto.PerceptionSignal.ColorB\x02\x10\x01\x12\x13\n\x0bis_flashing\x18\x03 \x01(\x08\x12\x15\n\nconfidence\x18\x04 \x01(\x02:\x01\x31\x12\x15\n\rtracking_time\x18\x05 \x01(\x03\";\n\x05\x43olor\x12\x07\n\x03OFF\x10\x00\x12\x07\n\x03RED\x10\x01\x12\n\n\x06YELLOW\x10\x02\x12\t\n\x05GREEN\x10\x03\x12\t\n\x05WHITE\x10\x04\"S\n\x11PerceptionSignals\x12\x11\n\ttime_meas\x18\x01 \x01(\x10\x12+\n\x06lights\x18\x02 \x03(\x0b\x32\x1b.car.proto.PerceptionSignal\"F\n\x18PerceptionSignalsRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\x05\x12\x16\n\nsignal_ids\x18\x02 \x03(\x04\x42\x02\x10\x01\"\xa2\x01\n\x19PerceptionSignalsResponse\x12\x12\n\nrequest_id\x18\x01 \x01(\x05\x12\x11\n\ttime_meas\x18\x02 \x01(\x10\x12\x30\n\x05\x63olor\x18\x03 \x01(\x0e\x32!.car.proto.PerceptionSignal.Color\x12\x15\n\nconfidence\x18\x04 \x01(\x02:\x01\x31\x12\x15\n\rtracking_time\x18\x05 \x01(\x03')
)



_PERCEPTIONSIGNAL_COLOR = _descriptor.EnumDescriptor(
  name='Color',
  full_name='car.proto.PerceptionSignal.Color',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OFF', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RED', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='YELLOW', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GREEN', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WHITE', index=4, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=193,
  serialized_end=252,
)
_sym_db.RegisterEnumDescriptor(_PERCEPTIONSIGNAL_COLOR)


_PERCEPTIONSIGNAL = _descriptor.Descriptor(
  name='PerceptionSignal',
  full_name='car.proto.PerceptionSignal',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='car.proto.PerceptionSignal.id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='colors', full_name='car.proto.PerceptionSignal.colors', index=1,
      number=2, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001')), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_flashing', full_name='car.proto.PerceptionSignal.is_flashing', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='confidence', full_name='car.proto.PerceptionSignal.confidence', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(1),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tracking_time', full_name='car.proto.PerceptionSignal.tracking_time', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _PERCEPTIONSIGNAL_COLOR,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=252,
)


_PERCEPTIONSIGNALS = _descriptor.Descriptor(
  name='PerceptionSignals',
  full_name='car.proto.PerceptionSignals',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='time_meas', full_name='car.proto.PerceptionSignals.time_meas', index=0,
      number=1, type=16, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lights', full_name='car.proto.PerceptionSignals.lights', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=254,
  serialized_end=337,
)


_PERCEPTIONSIGNALSREQUEST = _descriptor.Descriptor(
  name='PerceptionSignalsRequest',
  full_name='car.proto.PerceptionSignalsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='request_id', full_name='car.proto.PerceptionSignalsRequest.request_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='signal_ids', full_name='car.proto.PerceptionSignalsRequest.signal_ids', index=1,
      number=2, type=4, cpp_type=4, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001')), file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=339,
  serialized_end=409,
)


_PERCEPTIONSIGNALSRESPONSE = _descriptor.Descriptor(
  name='PerceptionSignalsResponse',
  full_name='car.proto.PerceptionSignalsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='request_id', full_name='car.proto.PerceptionSignalsResponse.request_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='time_meas', full_name='car.proto.PerceptionSignalsResponse.time_meas', index=1,
      number=2, type=16, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='color', full_name='car.proto.PerceptionSignalsResponse.color', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='confidence', full_name='car.proto.PerceptionSignalsResponse.confidence', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(1),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tracking_time', full_name='car.proto.PerceptionSignalsResponse.tracking_time', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=412,
  serialized_end=574,
)

_PERCEPTIONSIGNAL.fields_by_name['colors'].enum_type = _PERCEPTIONSIGNAL_COLOR
_PERCEPTIONSIGNAL_COLOR.containing_type = _PERCEPTIONSIGNAL
_PERCEPTIONSIGNALS.fields_by_name['lights'].message_type = _PERCEPTIONSIGNAL
_PERCEPTIONSIGNALSRESPONSE.fields_by_name['color'].enum_type = _PERCEPTIONSIGNAL_COLOR
DESCRIPTOR.message_types_by_name['PerceptionSignal'] = _PERCEPTIONSIGNAL
DESCRIPTOR.message_types_by_name['PerceptionSignals'] = _PERCEPTIONSIGNALS
DESCRIPTOR.message_types_by_name['PerceptionSignalsRequest'] = _PERCEPTIONSIGNALSREQUEST
DESCRIPTOR.message_types_by_name['PerceptionSignalsResponse'] = _PERCEPTIONSIGNALSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PerceptionSignal = _reflection.GeneratedProtocolMessageType('PerceptionSignal', (_message.Message,), dict(
  DESCRIPTOR = _PERCEPTIONSIGNAL,
  __module__ = 'perception_signal_pb2'
  # @@protoc_insertion_point(class_scope:car.proto.PerceptionSignal)
  ))
_sym_db.RegisterMessage(PerceptionSignal)

PerceptionSignals = _reflection.GeneratedProtocolMessageType('PerceptionSignals', (_message.Message,), dict(
  DESCRIPTOR = _PERCEPTIONSIGNALS,
  __module__ = 'perception_signal_pb2'
  # @@protoc_insertion_point(class_scope:car.proto.PerceptionSignals)
  ))
_sym_db.RegisterMessage(PerceptionSignals)

PerceptionSignalsRequest = _reflection.GeneratedProtocolMessageType('PerceptionSignalsRequest', (_message.Message,), dict(
  DESCRIPTOR = _PERCEPTIONSIGNALSREQUEST,
  __module__ = 'perception_signal_pb2'
  # @@protoc_insertion_point(class_scope:car.proto.PerceptionSignalsRequest)
  ))
_sym_db.RegisterMessage(PerceptionSignalsRequest)

PerceptionSignalsResponse = _reflection.GeneratedProtocolMessageType('PerceptionSignalsResponse', (_message.Message,), dict(
  DESCRIPTOR = _PERCEPTIONSIGNALSRESPONSE,
  __module__ = 'perception_signal_pb2'
  # @@protoc_insertion_point(class_scope:car.proto.PerceptionSignalsResponse)
  ))
_sym_db.RegisterMessage(PerceptionSignalsResponse)


_PERCEPTIONSIGNAL.fields_by_name['colors'].has_options = True
_PERCEPTIONSIGNAL.fields_by_name['colors']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))
_PERCEPTIONSIGNALSREQUEST.fields_by_name['signal_ids'].has_options = True
_PERCEPTIONSIGNALSREQUEST.fields_by_name['signal_ids']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))
# @@protoc_insertion_point(module_scope)
